# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GO_OBSERVER(object):
    def setupUi(self, GO_OBSERVER):
        GO_OBSERVER.setObjectName("GO_OBSERVER")
        GO_OBSERVER.resize(1183, 850)
        GO_OBSERVER.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(GO_OBSERVER)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 80, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 20, 131, 31))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(700, 80, 55, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 130, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 130, 55, 16))
        self.label_5.setObjectName("label_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(300, 300, 500, 500))
        self.tableWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        for i in range(0,9):
            self.tableWidget.setColumnWidth(i,50)
            for j in range(0,9):
                self.tableWidget.setRowHeight(j,50)
        # self.tableWidget.autoFillBackground()
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 180, 30, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(700, 180, 55, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(700, 230, 55, 16))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(540, 230, 45, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(700, 130, 55, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(290, 230, 55, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(130, 230, 111, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(290, 80, 55, 16))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(130, 180, 141, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(130, 80, 91, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(540, 130, 101, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 180, 55, 16))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        GO_OBSERVER.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GO_OBSERVER)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 26))
        self.menubar.setObjectName("menubar")
        GO_OBSERVER.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GO_OBSERVER)
        self.statusbar.setObjectName("statusbar")
        GO_OBSERVER.setStatusBar(self.statusbar)

        self.retranslateUi(GO_OBSERVER)
        QtCore.QMetaObject.connectSlotsByName(GO_OBSERVER)

    def retranslateUi(self, GO_OBSERVER):
        _translate = QtCore.QCoreApplication.translate
        GO_OBSERVER.setWindowTitle(_translate("GO_OBSERVER", "MainWindow"))
        self.label.setText(_translate("GO_OBSERVER", "Current Status"))
        self.label_2.setText(_translate("GO_OBSERVER", "GO OBSERVER"))
        self.label_4.setText(_translate("GO_OBSERVER", "Current Player"))
        self.label_5.setText(_translate("GO_OBSERVER", " "))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("GO_OBSERVER", "0"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("GO_OBSERVER", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("GO_OBSERVER", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("GO_OBSERVER", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("GO_OBSERVER", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("GO_OBSERVER", "5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("GO_OBSERVER", "6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("GO_OBSERVER", "7"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("GO_OBSERVER", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("GO_OBSERVER", "0"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("GO_OBSERVER", "1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("GO_OBSERVER", "2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("GO_OBSERVER", "3"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("GO_OBSERVER", "4"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("GO_OBSERVER", "5"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("GO_OBSERVER", "6"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("GO_OBSERVER", "7"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("GO_OBSERVER", "8"))
        self.label_6.setText(_translate("GO_OBSERVER", "Move"))
        self.label_9.setText(_translate("GO_OBSERVER", "Ranking"))
        self.label_12.setText(_translate("GO_OBSERVER", "Last Game Winner"))
        self.label_14.setText(_translate("GO_OBSERVER", "Players in current game"))
        self.label_15.setText(_translate("GO_OBSERVER", "Mode"))
        self.label_16.setText(_translate("GO_OBSERVER", "Total Players"))
